### PR TITLE
Api remade

### PR DESCRIPTION
**Pull request by escopecz**
This changes the API request URL from administrator to public URL.
### Testing

Try to authorize this plugin with this PR and register a new user to Joomla. The user should appear in the Mautic.

### CODE REVIEW

**Comment by RCheesley** [comment]
@escopecz does this PR need testing or do the conflicts need resolving first?

**Comment by RCheesley** [comment]
@escopecz can we do anything with these PR's or are they waiting on Mautic team to review & publish?

**Comment by escopecz** [comment]
Hi Ruth, it needs to resolve the conflicts and be properly tested by the community. My focus is on Mautic itself. Do you know someone from the Joomla community who would want to help maintaining this plugin?

**Comment by RCheesley** [comment]
@escopecz realise this is like, super old, but does it still need testing?

**Comment by escopecz** [comment]
Oops. This was fixing a API issue. But since it's so old it either was solved by another PR or is not used by anyone who'd need that. Let's close.

**Comment by RCheesley** [comment]
Was asking because someone was posting saying they couldn't get the users pushed into Mautic from Joomla so wasn't sure if this was fixing some problem there!

**Pull request closed without merging**
